WebApplication1/Models/catalog.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class catalog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public catalog()
        {
            this.products = new HashSet<product>();
        }
    
        public int id { get; set; }
        public string catalog_id { get; set; }
        public string catalog_name { get; set; }
        public string catalog_image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product> products { get; set; }
    }
}

WebApplication1/Areas/Admin/Controllers/catalogsController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Areas.Admin.Controllers
{
    public class catalogsController : Controller
    {
        private JP_QuanLySieuThiEntities1 db = new JP_QuanLySieuThiEntities1();

        // GET: Admin/catalogs
        public ActionResult Index(int? page)
        {
            System.IO.File.Copy(Server.MapPath("/Uploads/ImgNull/null.png"), Path.Combine(Server.MapPath("/Uploads/Catalogs/null.png")), true);
            System.IO.File.Copy(Server.MapPath("/Uploads/ImgNull/null.png"), Path.Combine(Server.MapPath("/Uploads/Products/null.png")), true);
            //if (search_admin_txt != null || search_admin_txt != "")
            //{
            //    return View(db.catalogs.Where(s => s.catalog_name.Contains(search_admin_txt.ToString())).ToList()); ;
            //}
            //else
            //{
            //    return View(db.catalogs.ToList());
            //}
            var catalog = db.catalogs.ToList();
            if (page == null) page = 1;
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(catalog.ToPagedList(pageNumber, pageSize));
        }

        // GET: Admin/catalogs/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            catalog catalog = db.catalogs.Find(id);
            if (catalog == null)
            {
                return HttpNotFound();
            }
            return View(catalog);
        }

        // GET: Admin/catalogs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/catalogs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( catalog catalog,HttpPostedFileBase img,string catalog_name)
        {
            string _path = Server.MapPath("~/Uploads/Catalogs/");
            if (!Directory.Exists(_path))
            {
                Directory.CreateDirectory(_path);
            }
            if (img != null)
            {
                string newFileName = DateTime.Now.Millisecond.ToString() + DateTime.Now.ToString("yyyyMMddHHmmss") + "Danhmuc" + ".jpg";
                string path0 = Path.Combine(_path + newFileName);

                // resize
                //WebImage new_img = new WebImage(img.InputStream);
                //if (new_img.Width > 500 || new_img.Height >280)
                //{
                //    new_img.Resize(500, 280);
                //}

                img.SaveAs(path0);

                catalog.catalog_image = newFileName;
            }
            else
            {
                catalog.catalog_image = "null.jpg";
            }
            catalog.catalog_id = DateTime.Now.ToString("yyyyMMddHHmmss") + "catalog_id";
            catalog.catalog_name = catalog_name;
            if (ModelState.IsValid)
            {
                db.catalogs.Add(catalog);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(catalog);
        }

        // GET: Admin/catalogs/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            catalog catalog = db.catalogs.Find(id);
            if (catalog == null)
            {
                return HttpNotFound();
            }
            return View(catalog);
        }

        // POST: Admin/catalogs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,catalog_id,catalog_name,catalog_image")] catalog catalog)
        {
            if (ModelState.IsValid)
            {
                db.Entry(catalog).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(catalog);
        }

        // GET: Admin/catalogs/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            catalog catalog = db.catalogs.Find(id);
            if (catalog == null)
            {
                return HttpNotFound();
            }
            return View(catalog);
        }

        // POST: Admin/catalogs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            catalog catalog = db.catalogs.Find(id);
            string physicalPath = "";
            // Delete old Image Upload
           if (catalog.catalog_image ==null || catalog.catalog_image == "")
            {
                 physicalPath = Path.Combine(Server.MapPath("~/Uploads/Catalogs/null.png"));
            }
            else
            {
                 physicalPath = Path.Combine(Server.MapPath("~/Uploads/Catalogs/"), catalog.catalog_image);
            }
           

            if (System.IO.File.Exists(physicalPath))
            {
                System.IO.File.Delete(physicalPath);
            }
            db.catalogs.Remove(catalog);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/Areas/Admin/Views/catalogs/Create.cshtml
@model WebApplication1.Models.catalog

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<div>
    @Html.ActionLink("Back", "Index")
</div>
<h2>Tạo mới</h2>

@using (Html.BeginForm("Create", "catalogs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>catalog</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.catalog_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.catalog_id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.catalog_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.catalog_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.catalog_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.catalog_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.catalog_image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="form-group">
                    <label class="form-label" for="inputLastName">Ảnh đại diện</label>
                    <div class="col-md-10">
                        <input class="ql-image" type="file" name="img" id="img" value="" onchange="ImagesFileAsURL()" />
                    </div>
                    <div class="style_displayImg" id="displayImg"></div>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}


<script type="text/javascript">

    function ImagesFileAsURL() {
        var fileSelected = document.getElementById('img').files;
        if (fileSelected.length > 0) {
            var fileToLoad = fileSelected[0];
            var fileReader = new FileReader();
            fileReader.onload = function (fileLoaderEvent) {
                var srcData = fileLoaderEvent.target.result;
                var newImage = document.createElement('img');
                newImage.src = srcData;
                document.getElementById('displayImg').innerHTML = newImage.outerHTML;
            }
            fileReader.readAsDataURL(fileToLoad);
        }
    }
</script>

WebApplication1/Areas/Admin/Views/catalogs/Delete.cshtml
@model WebApplication1.Models.catalog

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>catalog</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.catalog_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.catalog_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.catalog_image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.catalog_image)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplication1/Areas/Admin/Views/catalogs/Details.cshtml
@model WebApplication1.Models.catalog

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>catalog</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.catalog_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.catalog_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.catalog_image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.catalog_image)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.catalog_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebApplication1/Areas/Admin/Views/catalogs/Edit.cshtml
@model WebApplication1.Models.catalog

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>catalog</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.id, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.catalog_id)

        <div class="form-group">
            @Html.LabelFor(model => model.catalog_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.catalog_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.catalog_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.catalog_image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.catalog_image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.catalog_image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebApplication1/Areas/Admin/Views/catalogs/Index.cshtml
@*@model IEnumerable<WebApplication1.Models.catalog>*@
@model PagedList.IPagedList<WebApplication1.Models.catalog>
@using PagedList.Mvc;
@using PagedList;

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="col-md-12">
    <div style="display:flex;justify-content:space-between">
        <div>
            <h1 class="h3 d-inline align-middle">Danh Mục</h1>
        </div>
        <div>
            <nav aria-label="Page navigation example">

                @Html.PagedListPager(Model, page => Url.Action("Index", new { page }), new PagedListRenderOptions()
           {
               UlElementClasses = new[] { "pagination " },
               LiElementClasses = new[] { "page-item", "page-link" },
               LinkToPreviousPageFormat = "Trang trước",
               LinkToNextPageFormat = "Trang tiếp",
           })
            </nav>
            @*Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount*@
        </div>
    </div>








</div>
<div class="row">
    <div class="col-12 col-lg-8 col-xxl-8 d-flex">
        <div class="card flex-fill">
            <div class="card-header">
                <input type="hidden" name="khachhang" id="khachhang" value="danhmuc" />
                <h5 class="card-title mb-0">Danh sách</h5>
            </div>
            <table class="table table-borderless my-0">
                <thead>
                    <tr>
                        <th>Ảnh minh họa</th>
                        <th class="d-none d-xxl-table-cell">Tên danh mục</th>
                        <th class="d-none d-xl-table-cell"></th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                <div class="d-flex">
                                    <div class="flex-shrink-0">
                                        <div class="bg-light rounded-2">
                                            <img style="height:100px;width:100px" class="p-2" src="~/Uploads/Catalogs/@Html.DisplayFor(modelItem => item.catalog_image)">
                                        </div>
                                    </div>

                                </div>
                            </td>
                            <td class="d-none d-xxl-table-cell">
                                <strong> @Html.DisplayFor(modelItem => item.catalog_name)</strong>

                            </td>
                            <td class="d-none d-xl-table-cell">
                                @Html.ActionLink("!", "Edit", new { id = item.catalog_id }, new { @class = "btn btn-outline-info" })

                                @Html.ActionLink("X", "Delete", new { id = item.catalog_id }, new { @class = "btn btn-outline-danger" })

                            </td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
    </div>
    <div class="col-12 col-lg-4 col-xxl-4 d-flex" style="width:363px">
        <div class="card flex-fill w-100">
            <div class="card-header">
                <div class="card-actions float-end">
                    <h5 class="card-title mb-0">Thêm mới danh mục</h5>
                </div>
                <div class="card-body d-flex w-100 ">

                    @using (Html.BeginForm("Create", "catalogs", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()
                        <div class="m-sm-4">
                            <div class="text-center">
                                @*   <img src="img/avatars/avatar.jpg" alt="" class="img-fluid rounded-circle" width="132" height="132" />*@
                            </div>
                            <form>
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="mb-3">
                                    <label class="form-label">Tên danh mục</label>
                                    <input class="form-control form-control-lg" type="text" name="catalog_name" id="catalog_name" placeholder="Enter your catalog" />
                                </div>
                                <div class="mb-3">
                                    <label class="form-label">Image</label>
                                    <input class="form-control form-control-lg" type="file" name="img" id="img" onchange="ImagesFileAsURL()" />
                                    <div class="style_displayImg" id="displayImg"></div>
                                </div>

                                <div class="text-center mt-3">
                                    <button type="submit" class="btn btn-lg btn-primary">Create</button>
                                </div>
                            </form>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">

    function ImagesFileAsURL() {
        var fileSelected = document.getElementById('img').files;
        if (fileSelected.length > 0) {
            var fileToLoad = fileSelected[0];
            var fileReader = new FileReader();
            fileReader.onload = function (fileLoaderEvent) {
                var srcData = fileLoaderEvent.target.result;
                var newImage = document.createElement('img');
                newImage.src = srcData;
                document.getElementById('displayImg').innerHTML = newImage.outerHTML;
            }
            fileReader.readAsDataURL(fileToLoad);
        }
    }
</script>

@*@section scripts{

        <script>
            $(document).on('click', "button[name='btn_search']", function () {


                var _khachhang = $("#khachhang").val();
                var _search_admin = $("#search_admin").val();

                console.log(_khachhang);
                console.log(_search_admin);

            });

        </script>




    }*@